# This workflow will perform static code analysis using flake8, mypy, black and
# isort.

name: Static analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check import format using isort
      run: |
        # Check imports are correctly formated
        isort -c
    - name: Check formating with black
      run: |
        # Check formatting with black
        black --line-length 79 --check .
    - name: Type check with mypy
      run: |
        # Type check the autograd package, not tests, examples etc. 
        mypy --ignore-missing-imports autograd
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --ignore E203,W503 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  
